### ISSUE TITLE
Week 7 Code Review

### ISSUE THREAD

**Issue by ClassyElm** [ClassyElm/MinecraftJSONGenerator#11]
Hello, @pawaitemadisoncollege. Week 7 is ready to be reviewed.

This week, some of the key takeaways for me was understanding authentication and security for a web application from a high level. I would like to do some more work (like password hashing and salting), but I am feeling pretty comfortable so far.

This week, there were no major challenges (aside from setting up user roles prior to looking at the course content, which was a bad idea).

I had a couple problems and ideas to try, which resulted in using a variety of resources (some from my initial endeavors to make a user role feature at first).
* [CriteriaBuilder class with isNull method](https://docs.oracle.com/javaee/6/api/javax/persistence/criteria/CriteriaBuilder.html#isNull(javax.persistence.criteria.Expression)) when I was setting up potential null-value roles (for no role).
* [CriteriaQuery class](https://docs.oracle.com/javaee/6/api/javax/persistence/criteria/CriteriaQuery.html#where(javax.persistence.criteria.Predicate...)) to understand the Predicate and testing for null values.
* [CascadeType class](https://docs.oracle.com/javaee/6/api/javax/persistence/CascadeType.html) to understand valid options for mapping columns
* [On Delete Set Null mapping issues](https://stackoverflow.com/questions/8243400/on-delete-set-null-in-hibernate-in-onetomany) using Hibernate
* [Formatting strings with Log4J (for review)](https://stackoverflow.com/questions/30975026/log4j-implicit-string-formatting)
* [Attempt to get user role as a string](https://stackoverflow.com/questions/8680843/httpservletrequest-getremoteuser-vs-httpservletrequest-getuserprincipal-getn) (turns out it's a little difficult)
* [Principal interface](https://docs.oracle.com/javase/7/docs/api/java/security/Principal.html) to understand available methods associated with users and their roles.

**Comment by pawaitemadisoncollege** [comment]
Good work here @ClassyElm ! I like that you thought to restrict access to the servlets - often students only consider the jsps and forget about the servlets.

- [ ] Did you also create a META-INF/context.xml? I didn't see it in GitHub and wondered if everything was pushed.
- [ ] As you add more functionality to your project, remember to any restrict any resources as needed.

**Comment by ClassyElm** [comment]
I did add the context.xml, but I updated the .gitignore to restrict that file since it contained the user credentials for the tomcat MySQL user. Should that file be pushed since the web server is running locally?

**Comment by pawaitemadisoncollege** [comment]
Ah! That makes good sense! No need to push it.

**Comment by ClassyElm** [comment]
Sounds good. Thank you!
