### ISSUE TITLE
Week 8 Code Review

### ISSUE THREAD

**Issue by ClassyElm** [ClassyElm/MinecraftJSONGenerator#14]
Hello, @pawaitemadisoncollege. I finished everything from week 8, so I think it's ready to be reviewed.

This week, a key takeaway for me was learning how to interact with a RESTful web service. I think it's really powerful and hope to see more of them in the future. It was also nice to work with JSON mappers again since it has been a while for me.

I didn't really have any major challenges with the activities or exercise this week. The only problem I ran into was setting up the dependencies for the activities since I was creating the IntelliJ project with Gradle. Aside from that the only other (slight) challenge I had was completing the Dr Dobbs reading this week since the page does not contain the article anymore.

To fix the problem with the Dr Dobbs article, I used [the Wayback Machine](https://web.archive.org/web/20200814161818/https://www.drdobbs.com/web-development/restful-web-services-a-tutorial/240169069) to view an older version of the article.

For other issues, I used the following resources:
* [This stackoverflow post for association problems in the User entity](https://stackoverflow.com/questions/11746499/how-to-solve-the-failed-to-lazily-initialize-a-collection-of-role-hibernate-ex)
* [MVN repository for a variety of dependency links and copy-paste values](https://mvnrepository.com/)
* [This stackoverflow post about missing classes due to lack of needed dependencies](https://stackoverflow.com/questions/8186395/noclassdeffounderror-javax-activation-datasource/50559571)
* [Problems with the page redirecting when sending request to Star Wars API](https://stackoverflow.com/questions/18431440/301-moved-permanently)
* [Defining dependency properties for build.gradle file](https://stackoverflow.com/questions/38106576/how-do-i-define-a-variable-for-the-dependency-version-in-gradle)
* [Gson class documentation for parsing JSON and loading into objects](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.5/com/google/gson/Gson.html)

**Comment by pawaitemadisoncollege** [comment]
Very good @ClassyElm! 

No nitpicks as you are even using properties for the url (a detail many miss!)

**Comment by ClassyElm** [comment]
Glad to hear everything looks good. Thank you and have a nice rest of your break!
