### ISSUE TITLE
Week 9 Ready for Review

### ISSUE THREAD

**Issue by ClassyElm** [ClassyElm/MinecraftJSONGenerator#18]
Hey, @pawaitemadisoncollege. I completed exercise 9 here in my indie project, so that should be all good.

This week, I felt a key learning point was understanding how a RESTful service can be implemented using Java as well as how endpoints can be associated with the application.

I was challenged by the minimal lecture material this week. While it was enough to complete the activity, I felt like there was more independent research that I had to do this week (partially because I am curious and fall into rabbit holes of neat features).

This week, I had more problems with the time zone not saving in my database (I think I will have to change a configuration setting somewhere possibly). To solve this issue, I utilized the following resources:
* [Techniques to change MySQL global timezone](https://phoenixnap.com/kb/change-mysql-time-zone)
* [Time zone conversions](https://greenwichmeantime.com/time-zone/usa/central-time/)

I also had trouble with some odd Hibernate problems with vague error messages. It turns out, I had been using the "GROUP" keyword without realizing that Hibernate does not explicitly distinguish between the reserved keyword and a column in a table.
* [MySQL Reserved Keywords List](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-G)

Finally, I had some trouble while trying to get Gson to return JSON from any entity POJO. It turns out that Gson did not like certain fields in the entities, so I had to use the "@Expose" annotation to explicitly define which fields should be visible to Gson. In my endeavors, I used the following resources:
* [Java Produces Annotation docs](https://docs.oracle.com/javaee/7/api/javax/ws/rs/Produces.html)
* [Common MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)
* [QueryParam annotation example](https://mkyong.com/webservices/jax-rs/jax-rs-queryparam-example/)
* [Markdown comment syntax](https://stackoverflow.com/questions/4823468/comments-in-markdown)
* [Gson mapping lists to JSON](https://futurestud.io/tutorials/gson-mapping-of-arrays-and-lists-of-objects)
* [Gson "@Expose" annotation examples](https://www.baeldung.com/gson-exclude-fields-serialization)

Aside from those resources, I used the following additional resources as a review/tool/independent research:
* [jQuery Datatables](https://datatables.net/)
* [Online JavaScript minifier](https://www.minifier.org/)
* [Getting started with jQuery](https://www.w3schools.com/jquery/jquery_get_started.asp)
* [UriInfo documentation for retrieving many query parameters](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/UriInfo.html#getQueryParameters--)
* [MultivaluedMap return type from getQueryParameters method from UriInfo](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/MultivaluedMap.html)

**Comment by pawaitemadisoncollege** [comment]
Yes! There are many rabbit holes with this topic - often teams work their way through these topics together, but you were thorough enough with your work on week 9 that you uncovered some of those issues already.  For example, there are many different ways to produce json versions of the entities, as you probably noticed.  Jackson/Jersey can do this as well. 

I can't tell you how many times of seen a reserved word cause problems! Somebody needs to build, or find, a column name "linter"!

**Comment by ClassyElm** [comment]
Yes, that would be very helpful for debugging reserved words. I found a couple reserved word tools, but they seem to be more of a keyword lookup than an analyzer.

If everything else looks good, I will close up this issue. See you tomorrow!

**Comment by pawaitemadisoncollege** [comment]
Yes, closing this is a-ok.

**Comment by ClassyElm** [comment]
Sounds good. Thank you!
