### ISSUE TITLE
Project Checkpoint 1 Take 2

### ISSUE THREAD

**Issue by ClassyElm** [ClassyElm/MinecraftJSONGenerator#2]
Hello, @pawaitemadisoncollege. I updated the issues you identified during code review and hope everything looks good now.

From a broad view, I updated the following:
- Modified MVP user stories and added missing user stories
- Added load and save command wireframes
- Added _actual_ plan to project plan document

**Comment by pawaitemadisoncollege** [comment]
Very well done @ClassyElm. It's very clear that you've put a lot of time and thought into this already; that hard work will pay off! Looking forward to seeing the first working pieces of this!

**Comment by ClassyElm** [comment]
Thank you! I'm excited to get working on it.
