### ISSUE TITLE
Week 5 is Ready for Review

### ISSUE THREAD

**Issue by ClassyElm** [ClassyElm/MinecraftJSONGenerator#3]
Hey, @pawaitemadisoncollege! I completed this week's exercise. It was nice to implement everything directly into the project, especially since I had been falling behind on the progress.

This week, I felt a key point for me was working with generics, especially with the DAOs. I had heard and tried to learn about them on my own, but I never felt comfortable with them. While I still would like to practice more with generics (probably on my own), I was happy to learn about them.

Aside from some slight hiccups with the VM again, I did not run into any serious challenges this week.

The only real programming issue this week was an issue with not having set the fetch type to eager for the commands reference in the user entity class. The error message was descriptive enough, so I did not need to use any external resources aside from the course videos and assigned reading material ([the hibernate documentation was especially useful for associations though](https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#associations))

**Comment by pawaitemadisoncollege** [comment]
Great work implementing the GenericDao!  I think it's super slick, but it does take some time to think about and really understand it. I worry that some will just copy and paste and not entirely get it.  Looks like you are set up very well to easily hit checkpoint 2 next week!

- [ ] What do you think about testing the delete scenarios in one-to-many relationships more fully? For example, if a User is deleted, what should happen to their Commands? What if a Command is deleted? Write tests to make sure whatever _should_ happen, _does_ happen.
- [ ] Remember to check off completed items in your project plan by adding an "x" in to the brackets: `- [x] `
