### ISSUE TITLE
peer-review-week-06

### ISSUE THREAD

**Issue by mih9898** [ClassyElm/MinecraftJSONGenerator#4]
# Design/Code Review 1
​
## Project:
​
### Developer: Peter
​
### Reviewer: Mike T.
​
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.|1. Maybe providing some short example - what command exactly do how it makes life easier. For me who never plays Minecraft and who met scripting language only in writing macros, the problem statement sounds a little bit confusing without googling  <br>2. Other than this the problem statement is looking good for me|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. | 1. Design documentation is great. There's so much information about the project. <br> 2. In technologies that will be used there is no JSON API parser; I believe you say you will use GSON, so you could write it down |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>|1. In user-entity I would specify the wanted cascade behavior:  e.g: <code>@ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.DETACH})</code> . <br>Or you can adjust the cascade desired end behaviour  <br>2. Entities are documented and easy to understand how erd looks like|
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage.   |1. As I said if you will use API don't forget to update `gitignore` to hide your api-key(s) from properties <br>2. The code looks good so far

**Comment by pawaitemadisoncollege** [comment]
@mih9898 @ClassyElm Some sneaky printlns and stack traces. The search feature in GitHub does a good job finding these: 
![Screen Shot 2021-02-26 at 2 11 40 PM](https://user-images.githubusercontent.com/13874466/109350140-a0700980-783c-11eb-9df5-6f4b6e31e5dd.png)
