### ISSUE TITLE
Peer Review Week 6

### ISSUE THREAD

**Issue by noahaguilera** [ClassyElm/MinecraftJSONGenerator#5]
# Design/Code Review 1

### Reviewer: Noah

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.| The problem statement is really good at explaining the problem with Minecraft's in game commands and how tedious it can be to remember them. I think when talking about the commands adding some examples of hard to remember or complex commands could help visualize why having the ability to generate and store all your commands on your site is so helpful. Also piggy backing off that in your solution I think you could explain more of the benefits your site offers like storing the user's commands as well as viewing other peoples commands if you go that route.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. |I really liked your screen designs especially how they looked like a completed website. One suggestion on your generate command selection page maybe adding a little popup info box or description next to the commands saying what they are could be helpful. I see there is descriptions once you get to that specific command page but it would help reduce the user having to go back and forth between the pages to find which command they need to use. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>|Your data model and database look good so far. One thing to think about going forward which I'm sure you've already thought of is how you're going to implement the admin/report feature on your site. Are you going to add an admin column onto your user database or are you going create a admin database. Also with the report feature, if for example multiple users report a command and the admin responds to one of the reports and the command is deleted will all of the other reports be deleted at the same time as well, I'm not sure if you'd get errors otherwise. Just things to think about, its something I didn't think about till writing this so I'll have to make sure I do the same in my project.|
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage. |Code looks good so far, I know in our peer reviews you said you did most of the previous weeks work in the alternate option activities and you're going to implement them into your project. One small thing I'd say to add is some input boxes onto some jsps like a signup page so you can start testing to make sure the info you enter on the site makes its way into the database.

**Comment by pawaitemadisoncollege** [comment]
@noahaguilera and @ClassyElm - I agree with this: 

> adding some examples of hard to remember or complex commands

I think a picture could really drive this home!

One thing to add to this, there are some sneaky System.out.printlns out there.  Don't you love it when instructor-provided code has built-in standards "violations"? 

![Screen Shot 2021-02-26 at 11 07 31 AM](https://user-images.githubusercontent.com/13874466/109331872-ffc12000-7822-11eb-9f08-a5d12eb59f5c.png)
